background=0; //the outline
growing=false; //if the wallpaper is growing in size currently
shrinking=false; //if the wallpaper is shrinking in size currently
growingamount=0; //how much to grow/shrink it by every step
preview=false; //if this wallpaper is being previewed
middleX=256; //the target x when previewing this wallpaper
middleY=428; //the target y when previewing this wallpaper
wallpaperPreview=0; //the wallpaper preview object
disabled=false; //if interaction is disabled
text=0; //the quality text object
textY=0; //the quality text bottom row x coordinate
textX=0; //the quality text bottom row y coordinate
textMidX=322 //the quality text preview x coordinate
textMidY=190 //the quality text preview y coordinate
textGrowingamount=0; //how much to grow/shrink the quality text by every step

scaleSpeed=0; //over how many steps to scale the wallpaper and text
basePositionX=0; //bottom row x position
basePositionY=0; //bottom row y position